apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-03
spec:
  vendor: eduk8s.io
  title: "Jupyter on Kubernetes #3"
  description: A workshop exploring using JupyterHub to deploy Jupyter notebooks to Kubernetes
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-03
  content: github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-03
  duration: 30m
  session:
    budget: large
    applications:
      console:
        enabled: true
      terminal:
        enabled: true
        layout: split
    ingresses:
    - name: local-8000
      port: 8000
