apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-03
spec:
  title: "Jupyter on Kubernetes #3"
  description: A workshop exploring using JupyterHub to deploy Jupyter notebooks to Kubernetes.
  workshop:
    files:
    - image:
        url: $(image_repository)/lab-jupyter-on-k8s-03-files:latest
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: custom
      security:
        policy: baseline
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      registry:
        enabled: true
      vcluster:
        enabled: true
    ingresses:
    - name: local-8000
      authentication:
        type: none
      port: 8000
    - name: local-8001
      authentication:
        type: none
      port: 8001
    objects:
    - apiVersion: v1
      kind: Service
      metadata:
        namespace: $(workshop_namespace)
        name: $(session_namespace)-jupyterhub
      spec:
        type: ClusterIP
        selector:
          deployment: $(session_namespace)
        ports:
        - name: 8000-tcp
          port: 8000
          protocol: TCP
          targetPort: 8000
        - name: 8001-tcp
          port: 8001
          protocol: TCP
          targetPort: 8001
